version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  percona:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  neo4j:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  rethinkdb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  aerospike:
    driver: ${VOLUMES_DRIVER}
  caddy:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}
  mosquitto:
    driver: ${VOLUMES_DRIVER}
  confluence:
    driver: ${VOLUMES_DRIVER}
  sonarqube:
    driver: ${VOLUMES_DRIVER}
  cassandra:
    driver: ${VOLUMES_DRIVER}
  graylog:
    driver: ${VOLUMES_DRIVER}
  docker-in-docker:
    driver: ${VOLUMES_DRIVER}

services:

  ### Workspace Utilities ##################################
  workspace:
    build:
      context: ./workspace
      args:
        - CHANGE_SOURCE=false
        - SHELL_OH_MY_ZSH=false
        - UBUNTU_SOURCE=aliyun
        - BASE_IMAGE_TAG_PREFIX=latest
        - LARADOCK_PHP_VERSION=7.4
        - LARADOCK_PHALCON_VERSION=3.4.5
        - INSTALL_SUBVERSION=false
        - INSTALL_BZ2=false
        - INSTALL_GMP=false
        - INSTALL_XDEBUG=false
        - INSTALL_PCOV=false
        - INSTALL_PHPDBG=false
        - INSTALL_BLACKFIRE=false
        - INSTALL_SSH2=false
        - INSTALL_SOAP=false
        - INSTALL_XSL=false
        - INSTALL_LDAP=false
        - INSTALL_SMB=false
        - INSTALL_IMAP=false
        - INSTALL_MONGO=false
        - INSTALL_AMQP=false
        - INSTALL_CASSANDRA=false
        - INSTALL_GEARMAN=false
        - INSTALL_PHPREDIS=true
        - INSTALL_MSSQL=false
        - NVM_NODEJS_ORG_MIRROR=
        - INSTALL_NODE=true
        - NPM_REGISTRY=
        - INSTALL_PNPM=false
        - INSTALL_YARN=true
        - INSTALL_NPM_GULP=true
        - INSTALL_NPM_BOWER=false
        - INSTALL_NPM_VUE_CLI=true
        - INSTALL_NPM_ANGULAR_CLI=false
        - INSTALL_DRUSH=false
        - INSTALL_WP_CLI=false
        - INSTALL_DRUPAL_CONSOLE=false
        - INSTALL_AEROSPIKE=false
        - INSTALL_OCI8=false
        - INSTALL_V8JS=false
        - COMPOSER_GLOBAL_INSTALL=true
        - COMPOSER_AUTH=false
        - COMPOSER_REPO_PACKAGIST=
        - INSTALL_WORKSPACE_SSH=false
        - INSTALL_LARAVEL_ENVOY=false
        - INSTALL_LARAVEL_INSTALLER=false
        - INSTALL_DEPLOYER=false
        - INSTALL_PRESTISSIMO=false
        - INSTALL_LINUXBREW=false
        - INSTALL_MC=false
        - INSTALL_SYMFONY=false
        - INSTALL_PYTHON=false
        - INSTALL_IMAGE_OPTIMIZERS=false
        - INSTALL_IMAGEMAGICK=false
        - INSTALL_TERRAFORM=false
        - INSTALL_DUSK_DEPS=false
        - INSTALL_PG_CLIENT=false
        - INSTALL_PHALCON=false
        - INSTALL_SWOOLE=false
        - INSTALL_TAINT=false
        - INSTALL_LIBPNG=false
        - INSTALL_IONCUBE=false
        - INSTALL_MYSQL_CLIENT=false
        - INSTALL_PING=false
        - INSTALL_SSHPASS=false
        - INSTALL_INOTIFY=false
        - INSTALL_FSWATCH=false
        - INSTALL_AST=true
        - INSTALL_YAML=false
        - INSTALL_MAILPARSE=false
        - INSTALL_GIT_PROMPT=false
        - PUID=1000
        - PGID=1000
        - CHROME_DRIVER_VERSION=2.42
        - NODE_VERSION=node
        - YARN_VERSION=latest
        - DRUSH_VERSION=8.1.17
        - AST_VERSION=1.0.3
        - TZ=UTC
        - BLACKFIRE_CLIENT_ID="<client_id>"
        - BLACKFIRE_CLIENT_TOKEN="<client_token>"
        - INSTALL_POWERLINE=false
        - INSTALL_SUPERVISOR=false
        - INSTALL_FFMPEG=false
        - INSTALL_WKHTMLTOPDF=false
        - INSTALL_GNU_PARALLEL=false
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - docker-in-docker:/certs/client
      - ./php-worker/supervisord.d:/etc/supervisord.d
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "2222:22"
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
      - "8001:8000"
      - "4200:4200"
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=laradock
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
    command: ["sh","-c","composer install && php artisan queue:work"]

  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - CHANGE_SOURCE=false
        - BASE_IMAGE_TAG_PREFIX=latest
        - LARADOCK_PHP_VERSION=7.4
        - LARADOCK_PHALCON_VERSION=3.4.5
        - INSTALL_BZ2=false
        - INSTALL_GMP=false
        - INSTALL_XDEBUG=false
        - INSTALL_PCOV=false
        - INSTALL_PHPDBG=false
        - INSTALL_BLACKFIRE=false
        - INSTALL_SSH2=false
        - INSTALL_SOAP=false
        - INSTALL_XSL=false
        - INSTALL_SMB=false
        - INSTALL_IMAP=false
        - INSTALL_MONGO=false
        - INSTALL_AMQP=false
        - INSTALL_CASSANDRA=false
        - INSTALL_GEARMAN=false
        - INSTALL_MSSQL=false
        - INSTALL_BCMATH=true
        - INSTALL_PHPREDIS=true
        - INSTALL_MEMCACHED=false
        - INSTALL_OPCACHE=true
        - INSTALL_EXIF=false
        - INSTALL_AEROSPIKE=false
        - INSTALL_OCI8=false
        - INSTALL_MYSQLI=true
        - INSTALL_PGSQL=false
        - INSTALL_PG_CLIENT=false
        - INSTALL_POSTGIS=false
        - INSTALL_INTL=true
        - INSTALL_GHOSTSCRIPT=false
        - INSTALL_LDAP=false
        - INSTALL_PHALCON=false
        - INSTALL_SWOOLE=false
        - INSTALL_TAINT=false
        - INSTALL_IMAGE_OPTIMIZERS=true
        - INSTALL_IMAGEMAGICK=true
        - INSTALL_CALENDAR=false
        - INSTALL_FAKETIME=false
        - INSTALL_IONCUBE=false
        - INSTALL_APCU=false
        - INSTALL_CACHETOOL=false
        - INSTALL_YAML=false
        - INSTALL_RDKAFKA=false
        - INSTALL_GETTEXT=false
        - INSTALL_ADDITIONAL_LOCALES=false
        - INSTALL_MYSQL_CLIENT=false
        - INSTALL_PING=false
        - INSTALL_SSHPASS=false
        - INSTALL_MAILPARSE=false
        - INSTALL_PCNTL=false
        - ADDITIONAL_LOCALES="en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8"
        - INSTALL_FFMPEG=false
        - INSTALL_WKHTMLTOPDF=false
        - INSTALL_XHPROF=false
        - PUID=1000
        - PGID=1000
        - LOCALE=POSIX
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - docker-in-docker:/certs/client
    expose:
      - "9000"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=serverName=laradock
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - FAKETIME=-0
    depends_on:
      - workspace
    networks:
      - backend
    links:
      - docker-in-docker


  ### Apache Server ########################################
  apache2:
    build:
      context: ./apache2
      args:
        - PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}
        - PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}
        - DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${APACHE_HOST_LOG_PATH}:/var/log/apache2
      - ${APACHE_SITES_PATH}:/etc/apache2/sites-available
    ports:
      - "${APACHE_HOST_HTTP_PORT}:80"
      - "${APACHE_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=UTC
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  ### Laravel Echo Server #######################################
  laravel-echo-server:
    build:
      context: ./laravel-echo-server
    volumes:
      - ./laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT}:6001"
    links:
      - redis
    networks:
      - frontend
      - backend

  ### Docker-in-Docker ################################################
  docker-in-docker:
    image: docker:19.03-dind
    environment:
      DOCKER_TLS_SAN: DNS:docker-in-docker
    privileged: true
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - docker-in-docker:/certs/client
    expose:
      - 2375
    networks:
      - backend
